# Generated by Django 6.0.7 on 2026-07-11 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('businessName', models.CharField(db_column='businessName', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('extraInfo', models.TextField(blank=True, db_column='extraInfo', null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(blank=True, db_column='firstName', max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, db_column='lastName', max_length=100, null=True)),
                ('gstNo', models.CharField(blank=True, db_column='gst_no', max_length=100, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('fullName', models.CharField(blank=True, db_column='fullName', max_length=255, null=True)),
                ('avatarUrl', models.TextField(blank=True, db_column='avatarUrl', null=True)),
                ('notifications', models.TextField(blank=True, null=True)),
                ('visualPreference', models.CharField(db_column='visualPreference', default='light', max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('invoiceNumber', models.CharField(db_column='invoiceNumber', max_length=100)),
                ('orderNumber', models.CharField(blank=True, db_column='orderNumber', max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('createdDate', models.CharField(db_column='createdDate', max_length=100)),
                ('dueDate', models.CharField(db_column='dueDate', max_length=100)),
                ('subTotal', models.FloatField(db_column='subTotal')),
                ('discount', models.FloatField(default=0)),
                ('taxRate', models.FloatField(db_column='taxRate', default=0)),
                ('taxAmount', models.FloatField(db_column='taxAmount', default=0)),
                ('paidAmount', models.FloatField(db_column='paidAmount', default=0)),
                ('totalDue', models.FloatField(db_column='totalDue')),
                ('terms', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('hsnCode', models.CharField(blank=True, db_column='hsnCode', max_length=100, null=True)),
                ('quotationNumber', models.CharField(blank=True, db_column='quotationNumber', max_length=100, null=True)),
                ('client', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('adjustPercent', models.FloatField(db_column='adjustPercent', default=0)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('taxable', models.IntegerField(default=1)),
                ('hsnCode', models.CharField(blank=True, db_column='hsnCode', max_length=100, null=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.invoice')),
            ],
            options={
                'db_table': 'invoice_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('paymentMethod', models.CharField(db_column='paymentMethod', max_length=100)),
                ('paymentId', models.CharField(blank=True, db_column='paymentId', max_length=100, null=True)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('memo', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quoteNumber', models.CharField(db_column='quoteNumber', max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('createdDate', models.CharField(db_column='createdDate', max_length=100)),
                ('validUntilDate', models.CharField(db_column='validUntilDate', max_length=100)),
                ('subTotal', models.FloatField(db_column='subTotal')),
                ('discount', models.FloatField(default=0)),
                ('taxRate', models.FloatField(db_column='taxRate', default=0)),
                ('taxAmount', models.FloatField(db_column='taxAmount', default=0)),
                ('totalDue', models.FloatField(db_column='totalDue')),
                ('terms', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('allowComments', models.IntegerField(db_column='allowComments', default=0)),
                ('reasonForDecline', models.TextField(blank=True, db_column='reasonForDecline', null=True)),
                ('client', models.ForeignKey(db_column='clientId', on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('adjustPercent', models.FloatField(db_column='adjustPercent', default=0)),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('taxable', models.IntegerField(default=1)),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.quotation')),
            ],
            options={
                'db_table': 'quotation_items',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('settings_json', models.TextField(db_column='settings_json')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('recipient_to', models.TextField(db_column='recipient_to')),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('buttonText', models.TextField(blank=True, db_column='buttonText', null=True)),
                ('buttonUrl', models.TextField(blank=True, db_column='buttonUrl', null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'sent_emails',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('eventType', models.CharField(db_column='eventType', max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
